/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.tbosch.tools.consumption.gui;

import java.awt.event.KeyEvent;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;

import javax.annotation.PostConstruct;
import javax.swing.JFormattedTextField;
import javax.swing.UIManager;

import org.springframework.beans.factory.annotation.Autowired;

import de.tbosch.tools.consumption.service.DataService;

/**
 * 
 * @author Thomas Bosch
 */
public class MainFrame extends javax.swing.JFrame {

	private static final long serialVersionUID = 1L;

	@Autowired
	private DataService dataService;

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		jPanel1 = new javax.swing.JPanel();
		jPanel4 = new javax.swing.JPanel();
		valueFormattedTextField = new JFormattedTextField(NumberFormat.getIntegerInstance());
		dateFormattedTextField = new JFormattedTextField(new SimpleDateFormat("dd.MM.yyyy"));
		jLabel4 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jPanel5 = new javax.swing.JPanel();
		addButton = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		dataTable = new javax.swing.JTable();
		jPanel3 = new javax.swing.JPanel();
		msgLabel = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setResizable(false);
		getContentPane().setLayout(new java.awt.GridBagLayout());

		jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

		jPanel4.setLayout(new java.awt.GridBagLayout());

		valueFormattedTextField.setColumns(20);
		valueFormattedTextField.addKeyListener(new java.awt.event.KeyAdapter() {
			@Override
			public void keyReleased(java.awt.event.KeyEvent evt) {
				valueFormattedTextFieldKeyReleased(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
		jPanel4.add(valueFormattedTextField, gridBagConstraints);

		dateFormattedTextField.setColumns(20);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
		jPanel4.add(dateFormattedTextField, gridBagConstraints);

		jLabel4.setText("Wert:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
		gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
		jPanel4.add(jLabel4, gridBagConstraints);

		jLabel1.setText("Datum:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
		gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
		jPanel4.add(jLabel1, gridBagConstraints);

		jPanel1.add(jPanel4);

		addButton.setText("Hinzufügen");
		addButton.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				addButtonActionPerformed(evt);
			}
		});
		jPanel5.add(addButton);

		jPanel1.add(jPanel5);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
		getContentPane().add(jPanel1, gridBagConstraints);

		dataTable.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] { "Datum", "Wert" }) {
			Class[] types = new Class[] { java.lang.String.class, java.lang.Integer.class };
			boolean[] canEdit = new boolean[] { false, false };

			@Override
			public Class getColumnClass(int columnIndex) {
				return types[columnIndex];
			}

			@Override
			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jScrollPane1.setViewportView(dataTable);
		dataTable.getColumnModel().getColumn(0).setResizable(false);
		dataTable.getColumnModel().getColumn(1).setResizable(false);

		jPanel2.add(jScrollPane1);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
		getContentPane().add(jPanel2, gridBagConstraints);

		jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
		jPanel3.add(msgLabel);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		getContentPane().add(jPanel3, gridBagConstraints);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void valueFormattedTextFieldKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_valueFormattedTextFieldKeyReleased
		if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
			addButton.doClick();
		}
	}// GEN-LAST:event_valueFormattedTextFieldKeyReleased

	private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addButtonActionPerformed
		dataService.addData(dateFormattedTextField.getText(), valueFormattedTextField.getText());
		refreshTable();
	}// GEN-LAST:event_addButtonActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton addButton;
	private javax.swing.JTable dataTable;
	private javax.swing.JFormattedTextField dateFormattedTextField;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel msgLabel;
	private javax.swing.JFormattedTextField valueFormattedTextField;

	// End of variables declaration//GEN-END:variables

	/**
	 * Startet die GUI.
	 * 
	 * @throws Exception
	 */
	@PostConstruct
	public void init() throws Exception {
		UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
		setDefaultCloseOperation(DISPOSE_ON_CLOSE);
		initComponents();
		refreshTable();
		setLocationRelativeTo(null);
		setVisible(true);
	}

	private void refreshTable() {
		dataTable.setModel(new DataTableModel(dataService.readAllData()));
	}

}
